name: Continuous Integration Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Set Image Tag
        run: |
          echo "BUILD_IMAGE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Heroes with Maven
        run: |
          cd microservices/heros
          mvn -B clean package
          docker build -f microservices/heros/src/main/docker/Dockerfile.jvm -t $username/heroes_services .
          docker push $username/heroes_services .
      - name: Build Villain with Maven
        run: |
          cd microservices/villain
          mvn -B clean package
          docker build -f microservices/villain/src/main/docker/Dockerfile.jvm -t $username/villains_services .
          docker push $username/villains_services .
      - name: Build Fight with Maven
        run: |
          cd microservices/fight
          mvn -B clean package
          docker build -f microservices/fight/src/main/docker/Dockerfile.jvm -t $username/fight_services .
          docker push $username/fight_services .
